
	.align 2
voicegroup258:: @ 1133ca4
	voice_directsound 60, 0, DirectSoundWaveData_10cbeb4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cc274, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cc60c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cc60c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cc60c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cc60c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cc60c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cc8b8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cc8b8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cc8b8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cc8b8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cc8b8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cc8b8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c4d28, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c4d28, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c4d28, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c4d28, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c4d28, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c5638, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c5638, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c5638, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_108ab84, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_108ab84, 255, 0, 255, 235
