
	.align 2
voicegroup256:: @ 1133ac4
	voice_directsound 60, 0, DirectSoundWaveData_10c9a24, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c9d30, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c9d30, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c9d30, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c9fa0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c9fa0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c9fa0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c9fa0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c9fa0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c9fa0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c9fa0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10c9fa0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ca248, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ca248, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ca248, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ca248, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ca248, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ca248, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ca330, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ca330, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10480d0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10480d0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10480d0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10480d0, 255, 0, 255, 235
