
	.align 2
voicegroup248:: @ 1133464
	voice_directsound 60, 0, DirectSoundWaveData_10ac1b0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ac1b0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ac1b0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ad218, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ad218, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ad218, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10adfd8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10adfd8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10adfd8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10adfd8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10aed10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10aed10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10aed10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10aed10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a93b8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a93b8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a93b8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9614, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9614, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9614, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9614, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9614, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_108ab84, 255, 0, 255, 235
