
	.align 2
voicegroup293:: @ 1134bf8
	voice_directsound 60, 0, DirectSoundWaveData_110e238, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110e6dc, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110e6dc, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110e6dc, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110ea48, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110ea48, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110ed7c, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110ed7c, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_110ed7c, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1046914, 255, 252, 0, 235
