
	.align 2
voicegroup215:: @ 1131f34
	voice_directsound 60, 0, DirectSoundWaveData_10489d4, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1049b5c, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1049b5c, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1049b5c, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1049b5c, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_104abb4, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_104abb4, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_104abb4, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_104b8d4, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_104b8d4, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_104b8d4, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_104b8d4, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_104c43c, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_104cb60, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_104cb60, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_104cb60, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_104cfb4, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_104cfb4, 255, 253, 0, 235
