
	.align 2
voicegroup251:: @ 1133620
	voice_directsound 60, 0, DirectSoundWaveData_10b70c4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b70c4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b70c4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b9014, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b9014, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b9014, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b9014, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b9014, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ba7ac, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ba7ac, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ba7ac, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ba7ac, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ba7ac, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10bbf30, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10bbf30, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10bbf30, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10bbf30, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10bcf08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10bcf08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10bcf08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10bcf08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109c55c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109c55c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109c55c, 255, 0, 255, 235
