
	.align 2
voicegroup267:: @ 1134268
	voice_directsound 60, 0, DirectSoundWaveData_10d6cd4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d6cd4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d6cd4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d6dd0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d6dd0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d6e58, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d6e58, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d6e58, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
