
	.align 2
voicegroup247:: @ 1133398
	voice_directsound 60, 0, DirectSoundWaveData_10ab67c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10abd04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10abd04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10abd04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a97f4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a97f4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9fd0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9fd0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9fd0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10aaa74, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10aaa74, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ab0c8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ab0c8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ab490, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9614, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9614, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_108ab84, 255, 0, 255, 235
