
	.align 2
voicegroup261:: @ 1133efc
	voice_directsound 60, 0, DirectSoundWaveData_10cd288, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd748, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd748, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd748, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd748, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
