
	.align 2
voicegroup260:: @ 1133e30
	voice_directsound 60, 0, DirectSoundWaveData_10ccfe4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ccfe4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ccfe4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd0d8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd0d8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd0d8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd0d8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd174, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd174, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd1e4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd1e4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd23c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd23c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd23c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd23c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd23c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_108ab84, 255, 0, 255, 235
