
	.align 2
voicegroup250:: @ 11335cc
	voice_directsound 60, 0, DirectSoundWaveData_10b1f08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b1f08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b1f08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b1f08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b3c38, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b5c48, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10b5c48, 255, 0, 255, 235
