
	.align 2
voicegroup271:: @ 11344fc
	voice_directsound 60, 0, DirectSoundWaveData_10ea4ac, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ea4ac, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ea4ac, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ebac0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ebac0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ebac0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ebac0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_109c55c, 255, 0, 255, 235
