
	.align 2
voicegroup262:: @ 1133f44
	voice_directsound 60, 0, DirectSoundWaveData_10ce568, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ce568, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ce568, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ce568, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ced3c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ced3c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ced3c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ced3c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ced3c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cf53c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cf53c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cf53c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cfc6c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cfc6c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cfc6c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cfc6c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d018c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d018c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d018c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d05bc, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
