
	.align 2
voicegroup257:: @ 1133be4
	voice_directsound 60, 0, DirectSoundWaveData_10ca38c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ca38c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ca38c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ca38c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cac64, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cac64, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cac64, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cb2d4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cb2d4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cb930, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cbccc, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cbccc, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cbccc, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cbccc, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cbccc, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cbdc0, 255, 0, 255, 235
