
	.align 2
voicegroup266:: @ 11341b4
	voice_directsound 60, 0, DirectSoundWaveData_10d310c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d310c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d310c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d310c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d310c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d310c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d4824, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d4824, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d5b2c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d5b2c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d5b2c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d5b2c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d5b2c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cd748, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
