
	.align 2
voicegroup268:: @ 113431c
	voice_directsound 60, 0, DirectSoundWaveData_10d6ea4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d6ea4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d6ea4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d6ea4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d7aec, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cda0c, 255, 0, 255, 235
