
	.align 2
voicegroup269:: @ 113437c
	voice_directsound 60, 0, DirectSoundWaveData_10d8528, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10d9cc0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10dbba8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10dbba8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10dbba8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10dd938, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10dd938, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10dd938, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10df474, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10df474, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10df474, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10df474, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10df474, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10df474, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10df474, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10e0f2c, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10e0f2c, 255, 0, 255, 235
