
	.align 2
voicegroup259:: @ 1133db8
	voice_directsound 60, 0, DirectSoundWaveData_10ccbbc, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ccbbc, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cced4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cced4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10cced4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ca330, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ca330, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10480d0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10480d0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10480d0, 255, 0, 255, 235
