
	.align 2
voicegroup246:: @ 11332a8
	voice_directsound 60, 0, DirectSoundWaveData_10a6480, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a6d34, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a6d34, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a6d34, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a7894, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a97f4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a97f4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9fd0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9fd0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9fd0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10aaa74, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10aaa74, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10aaa74, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ab0c8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ab0c8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ab490, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10ab490, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9614, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_10a9614, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_108ab84, 255, 0, 255, 235
