
	.align 2
voicegroup288:: @ 1134a78
	voice_directsound 60, 0, DirectSoundWaveData_10f255c, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_10f255c, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_10fb8cc, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_10fb8cc, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_10fb8cc, 255, 254, 25, 235
