gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Birch.\p"
	.string "But I wish everyone would call me\n"
	.string "the Pokémon Professor.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Its roundness shows its gratitude\n"
	.string "that you are trying this game.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "What shape are you?$"

gText_Birch_BoyOrGirl::
	.string "Do you prefer to wear pants?\n"
	.string "Or skirts?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of Littleroot.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own doubles adventure\n"
	.string "is starting to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my Pokémon Lab.\p"
	.string "$"
