gText_MoveRelearner_Introduction: @ 820145C
    .string "I'm a Move Reminder.\p"
    .string "I'm trained to know the moves of\n"
    .string "Pokémon: every single one of them.\p"
    .string "I can teach a move to a Pokémon\n"
    .string "of yours if you'd like.$"

gText_MoveRelearner_TutorWhichMon: @ 82015A5
    .string "Which Pokémon needs reminding?$"

gText_MoveRelearner_TeachWhichMove: @ 82015C3
    .string "Which move should I teach?$"

gText_MoveRelearner_DontHaveMoveToTeachPokemon: @ 82015DE
    .string "Sorry…\p"
    .string "It doesn't appear as if I have any move\n"
    .string "I can teach that Pokémon.$"

gText_MoveRelearner_ComeBack: @ 8201653
    .string "If your Pokémon need to learn a move,\n"
    .string "come back any time.$"

gText_MoveRelearner_CantTeachEgg: @ 8201697
    .string "Eggs haven't forgotten anything.$"

