Common_MoveDeleter_Text_ICanMakeMonForgetMove: @ 821EAFD
    .string "Uh…\n"
    .string "Oh, yes, I'm the Move Deleter.\p"
    .string "I can make Pokémon forget their moves.\p"
    .string "Would you like me to do that?$"

Common_MoveDeleter_Text_WhichMonShouldForget: @ 821EB65
    .string "Which Pokémon should forget a move?$"

Common_MoveDeleter_Text_WhichMoveShouldBeForgotten: @ 821EB89
    .string "Which move should be forgotten?$"

Common_MoveDeleter_Text_MonOnlyKnowsOneMove: @ 821EBA9
    .string "{STR_VAR_1} knows only one move\n"
    .string "so it can't be forgotten…$"

Common_MoveDeleter_Text_MonsMoveShouldBeForgotten: @ 821EBDA
    .string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
    .string "That move should be forgotten?$"

Common_MoveDeleter_Text_MonHasForgottenMove: @ 821EC06
    .string "It worked to perfection!\p"
    .string "{STR_VAR_1} has forgotten\n"
    .string "{STR_VAR_2} completely.$"

Common_MoveDeleter_Text_ComeAgain: @ 821EC3F
    .string "Come again if there are moves that\n"
    .string "need to be forgotten.$"

Common_MoveDeleter_Text_EggCantForgetMoves: @ 821EC78
    .string "What?\n"
    .string "No Egg should know any moves.$"

Common_MoveDeleter_Text_CantForgetSurf: @ 821EC9C
    .string "Hm!\p"
    .string "Your {STR_VAR_1} doesn't seem willing\n"
    .string "to forget Surf.$"

