#ifndef GUARD_GAME_CORNER_EXPANSION_H
#define GUARD_GAME_CORNER_EXPANSION_H

#define GAME_CORNER_VAR_ID_CHECK        VAR_ROUTE114_STATE
#define GAME_CORNER_VAR_WINNINGS        VAR_UNUSED_0x40FF

#define FLAPPY_VAR_HIGH_SCORE        VAR_ROUTE113_STATE

#define DERBY_FLAG_NICKNAME             FLAG_UNUSED_0x023
#define DERBY_FLAG_RESET                FLAG_UNUSED_0x024
#define DERBY_VAR_RACER_NAME_1          VAR_ROUTE105_STATE
#define DERBY_VAR_RACER_NAME_2          VAR_ROUTE106_STATE
#define DERBY_VAR_RACER_NAME_3          VAR_ROUTE107_STATE
#define DERBY_VAR_RACER_NAME_4          VAR_ROUTE108_STATE
#define DERBY_VAR_RACER_NAME_5          VAR_ROUTE109_STATE
#define DERBY_VAR_RACER_NAME_6          VAR_ROUTE111_STATE
#define DERBY_VAR_RACER_1               VAR_ROUTE122_STATE
#define DERBY_VAR_RACER_2               VAR_ROUTE123_STATE
#define DERBY_VAR_RACER_3               VAR_ROUTE124_STATE
#define DERBY_VAR_RACER_4               VAR_ROUTE125_STATE
#define DERBY_VAR_RACER_5               VAR_ROUTE126_STATE
#define DERBY_VAR_RACER_6               VAR_ROUTE127_STATE

#define FLIP_VAR_LEVEL                  VAR_UNUSED_0x40FE

#endif // GUARD_GAME_CORNER_EXPANSION_H
